server:
  restart: always
  build: ./server
  expose:
    - "8000"
  links:
    - postgres:postgres
  command: /usr/local/bin/gunicorn -w 2 -b :8000 rr.app:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - server:server

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

test:
  restart: always
  build: ./server
  links:
    - postgres:postgres
  # command: py.test tests
  # environment:
    # - PYTHONPATH='/usr/src/app'
