runtime: python
env: flex
entrypoint: gunicorn -b :$PORT rr.app:app

runtime_config:
  python_version: 3

#[START env]
env_variables:
  # Replace user, password, database, and instance connection name with the values obtained
  # when configuring your Cloud SQL instance.
  CONFIG_ENV: prod
#[END env]

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
  cloud_sql_instances: round-robin-prod:us-central1:app-engine

#[END cloudsql_settings]
