runtime: python
env: flex
entrypoint: honcho start flask
runtime_config:
  python_version: 3
env_variables:
  CONFIG_ENV: prod
  PYTHONPATH: .
  FLASK_APP: rr/app.py
beta_settings:
  cloud_sql_instances: round-robin-prod:us-central1:app-engine
