runtime: python
env: flex
entrypoint: gunicorn -b :$PORT rr.app:app
runtime_config:
  python_version: 3
env_variables:
  CONFIG_ENV: prod
beta_settings:
  cloud_sql_instances: round-robin-prod:us-central1:app-engine
