"""initial

Revision ID: caf243e44c46
Revises: 
Create Date: 2017-03-06 14:10:39.788425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf243e44c46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('prompt', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fb_id', sa.String(length=1000), nullable=True),
    sa.Column('fb_access_token', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('pic_url', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fb_id')
    )
    op.create_table('composition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('friend_a_id', sa.Integer(), nullable=False),
    sa.Column('friend_b_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['friend_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('friend_a_id', 'friend_b_id')
    )
    op.create_table('view',
    sa.Column('composition_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composition_id'], ['composition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view')
    op.drop_table('friendships')
    op.drop_table('composition')
    op.drop_table('users')
    op.drop_table('prompt')
    # ### end Alembic commands ###
