"""User.scheduled_onesignal_notifications

Revision ID: f7961e343f94
Revises: 5a5ff38552ff
Create Date: 2017-03-29 06:30:15.511033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7961e343f94'
down_revision = '5a5ff38552ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_onesignal_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onesignal_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onesignal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_onesignal_notifications')
    # ### end Alembic commands ###
