"""second

Revision ID: 18f11b193a34
Revises: 3ac5041a41be
Create Date: 2017-03-04 21:53:58.409274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18f11b193a34'
down_revision = '3ac5041a41be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('composition', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('composition', 'create_date')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('users', 'create_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'created_at')
    op.add_column('composition', sa.Column('create_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('composition', 'created_at')
    # ### end Alembic commands ###
